# Generated by Django 2.0.7 on 2019-01-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Books',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Internet_Data',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('login_time', models.DateField()),
                ('exit_time', models.DateField()),
                ('duration', models.IntegerField()),
                ('flow', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='One_Cartoon',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Grade',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('course_name', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('grade_point', models.FloatField()),
                ('category', models.CharField(choices=[('A', '正常考试'), ('B', '补考'), ('C', '重修')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=20)),
                ('_class', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('X', '女'), ('Y', '男')], max_length=5)),
                ('age', models.IntegerField()),
                ('birthplace', models.CharField(max_length=20)),
                ('politics_status', models.CharField(choices=[('A', '党员'), ('B', '预备党员'), ('C', '共青团员'), ('D', '其他')], max_length=10)),
                ('category', models.CharField(choices=[('A', '农村应届'), ('B', '农村往届'), ('C', '城市应届'), ('D', '城市往届'), ('E', '其他')], max_length=10)),
                ('major', models.CharField(max_length=20)),
                ('family_background', models.CharField(choices=[('A', '贫困'), ('B', '非贫困')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='student_grade',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Info'),
        ),
        migrations.AddField(
            model_name='one_cartoon',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Info'),
        ),
        migrations.AddField(
            model_name='internet_data',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Info'),
        ),
        migrations.AddField(
            model_name='borrow_books',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Info'),
        ),
        migrations.AddField(
            model_name='award',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Info'),
        ),
    ]
