# Generated by Django 2.0.7 on 2019-01-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='educational_history',
            field=models.CharField(choices=[('A', '本科'), ('B', '硕士'), ('C', '博士')], default='A', max_length=10),
        ),
    ]
