# Generated by Django 2.0.7 on 2019-01-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_borrow_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_books',
            name='category',
            field=models.CharField(max_length=8),
        ),
    ]
