# Generated by Django 2.0.7 on 2019-01-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190114_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_books',
            name='callno',
            field=models.CharField(default='XXX', max_length=8),
            preserve_default=False,
        ),
    ]
