# Generated by Django 2.0.7 on 2019-01-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_borrow_books_callno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_grade',
            name='grade_point',
        ),
    ]
