# Generated by Django 2.0.7 on 2019-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190115_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_cartoon',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
